"""add follow model and update user relationships

Revision ID: 2aaf5a43be0e
Revises: 70b7b39b8ec9
Create Date: 2026-01-19 17:12:43.592427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aaf5a43be0e'
down_revision: Union[str, Sequence[str], None] = '70b7b39b8ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
