"""add otp fields to users

Revision ID: d82905dd9d29
Revises: 
Create Date: 2026-01-19 12:40:06.725615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82905dd9d29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_used')
    op.drop_column('users', 'expires_at')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
